kind: Service
apiVersion: v1
metadata:
 name: spring
spec:
 selector:
 # Esta etiqueta la usa k8s para buscar el pod
 # al que le enviara el trafico. Un error aqui 
 # hara que no funcione el ruteo.
 app: spring
 ports:
 - protocol: TCP
 port: 8080